apiVersion: v1
kind: Namespace
metadata:
  name: linkerd
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: k8s-linkerd-repo-helm-chart-linkerd
    meta.helm.sh/release-namespace: linkerd
