# Placeholder: Replace with the output of `linkerd install --crds`
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serviceprofiles.linkerd.io
spec:
  group: linkerd.io
  names:
    kind: ServiceProfile
    listKind: ServiceProfileList
    plural: serviceprofiles
    singular: serviceprofile
  scope: Namespaced
  versions:
    - name: v1alpha2
      served: true
      storage: true
