apiVersion: v1
kind: ServiceAccount
metadata:
  name: crd-patch
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-patch-role
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-patch-rolebinding
subjects:
  - kind: ServiceAccount
    name: crd-patch
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: crd-patch-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: patch-linkerd-crd-ownership
  namespace: kube-system
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: crd-patch
      containers:
        - name: patch
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "🔧 Patching Gateway API CRD"
              kubectl label crd httproutes.gateway.networking.k8s.io app.kubernetes.io/managed-by=Helm --overwrite || true
              kubectl annotate crd httproutes.gateway.networking.k8s.io \
                meta.helm.sh/release-name=linkerd \
                meta.helm.sh/release-namespace=linkerd --overwrite || true

              echo "🔧 Patching Linkerd CRDs for Helm ownership"
              for crd in \
                authorizationpolicies.policy.linkerd.io \
                httproutes.policy.linkerd.io \
                meshtlsauthentications.policy.linkerd.io \
                serverauthorizations.policy.linkerd.io \
                servers.policy.linkerd.io; do
                echo "🔧 Patching $crd"
                kubectl annotate crd $crd \
                  meta.helm.sh/release-name=linkerd \
                  meta.helm.sh/release-namespace=linkerd --overwrite || true
              done
